export const CREATE_MARKER = 'CREATE_MARKER';
export const UPDATE_MARKER = 'UPDATE_MARKER';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const CHANGE_MARKER_CIRCLE = 'CHANGE_MARKER_CIRCLE';